### ISSUE TITLE
SX Command on different drive

### ISSUE THREAD

**Issue by kenmartin-unix** [MiguelVis/samarux#1]
I have SX and X files installed on A0:

If I am on for example B2: and I do:

SX ls -l

Says it can't find samaruX.

I can do SC, but it can't find any of the X files. They only seem to work if I am on A0:

If from A0: sc ls -l   it works.

Am I doing something wrong?

Also is the code for LS.X available? Could other X programs be created?

Thanks!

**Comment by MiguelVis** [comment]
Hi @kenmartin-unix 

Just use the `BINDIR` environment variable as told in the docs.

For example, you could add this to your SamaruX profile:

```
env BINDIR A0:
```

or even:

```
diralias bin a0:
env BINDIR bin:
```

The source code for LS is named `sx_ls.c`.

And yes, it's possible to create other X programs, there are some examples in the repository as `cal`, `banner` or `strings`.

**Comment by kenmartin-unix** [comment]
Miguel correct me if I am wrong.

The source is intended to be compiled on a Windows machine, yes?

Where does one get the "cpm" command for Windows? And after
compiling the result can be move to the CP/M machine?

It can not be compiled on Linux, yes?

Thanks
